# Generated by Django 3.0.1 on 2021-01-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='purchase_no',
            new_name='sales_no',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='product',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
