# Generated by Django 3.0.1 on 2021-01-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210118_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
