# Generated by Django 3.0.1 on 2021-01-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_sales_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
