# Generated by Django 3.0.1 on 2021-01-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210121_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
