# Generated by Django 3.0.1 on 2021-01-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_purchase_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='../static/images/'),
        ),
    ]
