# Generated by Django 3.0.1 on 2021-01-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210125_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='File',
        ),
        migrations.AddField(
            model_name='purchase',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='./static/images/'),
        ),
    ]
