# Generated by Django 3.0.1 on 2021-01-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210126_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='./static/images/'),
        ),
    ]
