# Generated by Django 3.0.1 on 2021-01-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210126_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='image',
            new_name='File',
        ),
    ]
