# Generated by Django 3.0.1 on 2021-01-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20210127_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='File',
            field=models.ImageField(blank=True, null=True, upload_to='./inventory/static/images'),
        ),
    ]
