# Generated by Django 3.0.1 on 2021-01-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210127_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='File',
            new_name='image',
        ),
    ]
