# Generated by Django 3.0.1 on 2021-02-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_stock_hsn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='address',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='phone',
        ),
    ]
