# Generated by Django 3.0.1 on 2021-02-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_auto_20210201_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='size',
            new_name='gst_no',
        ),
        migrations.AddField(
            model_name='sales',
            name='gst_rate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
