# Generated by Django 3.0.1 on 2021-02-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_auto_20210201_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='hsn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
