# Generated by Django 3.0.1 on 2021-02-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_sales_hsn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='gst_rate',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
