# Generated by Django 3.0.1 on 2021-02-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_auto_20210202_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='gst_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
